name: LaTeX document compiler
on: push
  # You may pin to the exact commit or the version.
  # uses: Sakul6499/GitHub-Action-LaTeX@84484d7411f7131bb8518650eabdb1bc155500e6
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: Sakul6499/GitHub-Action-LaTeX@v1.0.0
        with:
          latex_main_file: notes.tex
          working_directory: Skript/
          latex_compiler: xelatex
          latex_compiler_arguments: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode"
          system_packages: "gcc"
          pre_task: 'echo "''Hello, World!'' from BEFORE compilation."'
          post_task: 'echo "''Hello, World!'' from AFTER compilation."'
